language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - pytest
  - flake8 main.py sqlcontacts.py
  - pylint main.py sqlcontacts.py
  - mypy --ignore-missing-imports .
